os:
  editPreset: 'zed'
gui:
  showCommandLog: false
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  enlargedSideViewLocation: top
  nerdFontsVersion: 3
  border: single
git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" $(defaults read -g AppleInterfaceStyle 2>/dev/null && echo "--dark --features=zenbones-dark" || echo "--light --features=zenbones-light")
customCommands:
  - key: 'G'
    command: 'gh {{.Form.GitHubCommand}}'
    description: "GitHub"
    context: 'global'
    prompts:
      - type: 'menu'
        title: 'GitHub'
        key: 'GitHubCommand'
        options:
          - value: 'pr view --web'
            name: 'Pull Request - View (web)'
          - value: 'pr create'
            name: 'Pull Request - Create'
          - value: 'pr create -d'
            name: 'Pull Request - Create (Draft)'
          - value: 'pr list'
            name: 'Pull Request - List'
    output: terminal
  - key: "R"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: >-
          gh pr list --json number,title,headRefName,updatedAt --template '{{`{{range .}}{{printf "#%v: %s - %s (%s)" .number .title .headRefName (timeago .updatedAt)}}{{end}}`}}'
        filter: '#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+).*'
        valueFormat: '{{.number}}'
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'
