os:
  editPreset: 'zed'
gui:
  showCommandLog: false
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  enlargedSideViewLocation: top
  border: single
git:
  pagers:
    - colorArg: always
      pager: |
        delta --paging=never --line-numbers --hyperlinks \
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
customCommands:
  - key: '<c-g>'
    description: "GitHub"
    commandMenu:
      - key: v
        command: 'gh pr view --web'
        description: 'pr | view | current branch | web'
        context: status, files
      - key: v
        command: 'gh pr view --web {{.SelectedLocalBranch.Name}}'
        description: 'pr | view | selected branch | web'
        context: localBranches
      - key: v
        command: 'gh pr view --web {{.SelectedRemoteBranch.Name}}'
        description: 'pr | view | selected branch | web'
        context: remoteBranches

      - key: V
        command: 'gh pr view'
        description: 'pr | view | current branch | cli'
        context: status, files
      - key: V
        command: 'gh pr view {{.SelectedLocalBranch.Name}}'
        description: 'pr | view | selected branch | cli'
        context: localBranches
      - key: v
        command: 'gh pr view {{.SelectedRemoteBranch.Name}}'
        description: 'pr | view | selected branch | cli'
        context: remoteBranches

      - key: c
        command: 'gh pr create'
        description: 'pr | create'
        context: global
      - key: C
        command: 'gh pr create --draft'
        description: 'pr | create | draft'
        context: global
