#!/bin/bash

# Source settings file
. $HOME/.scripts/dzen2/settings

# Source dzen command
. $HOME/.scripts/dzen2/command

while :; do

  echo " ^fg($MAGENTA) \
$(windowname 40 | tr '[:lower:]' '[:upper:]') \
^fg($FG) | \
^fg($BLUE) $(date +%H:%M)   "

  sleep $SLEEP
done | $DZEN
