#!/bin/bash

if [ -z "${HELIX_THEME_LIGHT}" ]; then
  echo "Please set env var HELIX_THEME_LIGHT"
  exit 1
fi

if [ -z "${HELIX_THEME_DARK}" ]; then
  echo "Please set env var HELIX_THEME_DARK"
  exit 1
fi

HELIX_CONFIG_FILE="${XDG_CONFIG_HOME}/helix/config.toml"

# Detect system theme: "Dark" | "Light"
system_theme=$(defaults read -g AppleInterfaceStyle 2>/dev/null || echo "Light")

if [ "${system_theme}" == "Dark" ]; then
  helix_theme="${HELIX_THEME_DARK}"
else
  helix_theme="${HELIX_THEME_LIGHT}"
fi

temp_file=$(mktemp)
trap "rm -f ${temp_file}" EXIT

(echo "theme = \"${helix_theme}\""; echo; cat ${HELIX_CONFIG_FILE}) | cat > ${temp_file}

hx -c ${temp_file} $*
